name: Tests
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '**.md'
    - 'LICENSE'

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
    - name: Test with the Go CLI
      run: go test -tags=unit -v ./...
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UnitTestsOutput
        path: |
          tests/out/*
          !tests/out/.gitkeep

  intetration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
    - name: Test with the Go CLI
      run: go test -tags=integration -v ./...
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: IntegrationTestsOutput
        path: |
          tests/out/*
          !tests/out/.gitkeep
